version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: pnoker/dc3-web:1.0
    restart: always
    ports:
      - 443:443
    container_name: dc3-web
    hostname: dc3-web
    volumes:
      - nginx:/var/log/nginx
    networks:
      dc3net:
        aliases:
          - dc3-web

volumes:
  nginx:

networks:
  dc3net:
    driver: 'bridge'
...
